- name: set up webserver
  hosts: all
  tasks: 
    - name: ensure httpd is at the latest version
      apt:
        name: httpd
        state: latest
    - name: start nginx
      service: 
        name: httpd
        state: started
        enabled: yes 