- name: Ansible vault 
  become: yes
  hosts: webservers
  vars_files:
     /home/ansible/unit04/vault.yml
  tasks:
   - name: add user and set password
     user:
        name: shyam
        password: "{{mypass | password_hash('sha512')}}"