- name: Ansible vault 
  become: yes
  hosts: webservers
  vars:
     mypass: welcome
  tasks:
   - name: add user and set password
     user:
        name: shyam
        password: "{{mypass | mypass_hash('sha512')}}"