- name: pass the varaible through command and precedence of command line varaible is more than playbook varaible
  gather_facts: false
  become: true
  hosts: webservers
  vars:
      name: ravi
      pw: redhat
  tasks: 
    - name: add user and give me password
      user: 
         name: "{{ name }}"
         password: "{{ pw | password_hash('sha512')}}" 
    