- name: check if the service is present on node 
  hosts: webservers
  become: yes 
  gather_facts: true
  tasks:
     - name: service name to be check 
       service:
          name: httpd
          state: restarted 
       register: xyz
     - name: display on screen output 
       debug:
           var: xyz.changed
