- name: check if the service is present on node 
  hosts: webservers
  become: yes 
  gather_facts: true
  tasks:
     - name: service name to be check 
       service:
          name: httpd
          state: restarted 
       register: xyz
#     - name: display on screen output 
#      debug:
#           var: xyz.changed = false
      - name: Restart the service if it is already running
        ansible.builtin.systemd:
           name: your_service_name
           state: started
       when: service_status.changed : false