- name: check if the service is present on node 
  hosts: webservers
  become: yes 
  gather_facts: true
  tasks:
     - name: service name to be check 
       service:
          name: httpd
          state: loaded
       register: xyz

     - name: Restart the service if it is already running
       service:
           name: httpd
           state: started
       when: service_status.changed 