- name: failed when example demo 
  hosts: webservers
  become: true 
  tasks: 
     - debug:
           msg: "check the os before installing mariadb package " 
       failed_when: ansible_distribution != 'CentOS'
     - name: install httpd package
       yum: 
        name: httpd
        state: installed

         