- name: notify and handlers example
  hosts: webservers
  gather_facts: false
  become: true
  tasks:
     - name: edit if the configuration file of httpd server is edited 
       copy:
          src: /etc/httpd/conf/httpd.conf
          dest: /etc/httpd/conf/httpd.conf
          remote_src: true
       notify: httpd
handlers:
     - name: httpd
       service:
             name: httpd
             state: restarted

      

