- name: set up webserver, firewalld and copy file 
  gather_facts: false
  become: true
  hosts: webservers
  tasks: 
    - name: ensure httpd is at the latest version
      yum:
        name: 
          - httpd
          - firewalld
        state: latest
    - name: start httpd and firewalld
      service: 
        name: httpd
        state: started
        enabled: true

    - name: copy file from /tmp/index.html to /var/www/html
      copy: 
        src: /tmp/index.html
        dest: /var/www/html
        

    - name: start  firewalld
      service: 
        name: firewalld
        state: started
        enabled: true

    - name: port firewalld
      firewalld: 
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: true