- name: example of nested loop 
  hosts: webservers 
  become: yes
  tasks:
    - name: add user through nested loop in multiple groups  
      user:
         name: "{{ item[0] }}"
         groups: "{{ item[1] }}"
         state: present 
         append: yes 

      with_nested:
          - { 'ram1' , 'manish' , 'shyam1' }
          - { 'staff' , 'guests' , 'manager' }
