- hosts: webservers
  tasks:
   - file:
        path: /tmp/test
        state: directory
   - copy:
        src: /etc/fstab
        dest: /tmp/test
   - service:
        name: crond
        state: restarted