- name: Template loops example 
  hosts: all
  gather_facts: true 
  become: yes 
  tasks: 
     - name: copy jinja file to dev groups machine 
       template:
           src: /home/ansible/Ansible/hostdetails.j2
           dest: /etc/myhosts