- name: conditional template example 
  
  
  hosts: all
 
  tasks: 
    - name: check the existance of disk 
      stat:
          path: /dev/nvme0n1
      register: xyz
    
    
    - name: copy hardware report to /etc/myhosts
      template:
        src: /home/ansible/Ansible/hwreport.j2
        dest: /home/ansible/Ansible/
        