- name: register variable use case  
  become: yes 
  hosts: webservers
 
  tasks: 
    - name: check the hardware mode status 
      command: uname -m
      register: xyz
    - debug:
         var: xyz.stdout    
    
    - name: copy hardware number to /etc/myhosts
      copy:
        content: "this is the hardware mode {{ xyz.stdout }} "
        dest: /etc/myhosts
        