 
- name: add users from the managed node
  hosts: webservers
  become: yes  # This playbook needs to run with root privileges
  vars_files:
      /home/ansible/unit04/userlist.yml
    

  tasks:
    - name: add specified users
      user:
        name: "{{ item }}"
        state: present
        # remove: yes  # This attempts to remove the user's home directory and mail spool
      with_items: "{{ users_to_add }}"

           
