- name: install httpd 
  hosts: webservers
  become: yes
  tasks: 
      - name: install httpd server 
        yum:
          name: httpd
          state: installed
        tags: ['never' , 'install']

      - name: remove httpd server 
        yum: 
          name: httpd
          state: absent
        tags: ['never' , 'removed'] 