 
- name: add users from the managed node
  hosts: webservers
  become: yes  # This playbook needs to run with root privileges
  
    

  tasks:
    - name: add specified users from text file 
      user:
        name: "{{ item }}"
        state: present
        # remove: yes  # This attempts to remove the user's home directory and mail spool
      loop: "{{ lookup('file', '/home/ansible/unit04/simple').spiltlines() }}"

           
